name: CI

on:
  push:
    branches: [ master, github-action ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    name: Test on go ${{ matrix.go-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version: [ 1.11.4, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: |
          ./test.sh
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
